# Generated by Django 4.2.16 on 2024-10-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment_management", "0003_referee_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("upcoming", "Upcoming"),
                    ("ongoing", "Ongoing"),
                    ("complete", "Complete"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="upcoming",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["appointment_date", "appointment_time"],
                name="Appointment_appoint_be0173_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["referee", "status"], name="Appointment_referee_62b048_idx"
            ),
        ),
    ]
